"""initial version

Revision ID: 834275a17daa
Revises: 
Create Date: 2023-07-20 13:13:56.683012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834275a17daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_count',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('url_index', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('word', 'url_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_count')
    # ### end Alembic commands ###
